version: '3.7'

services:
  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqlASW
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=example_db